version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
