version: 2

build:
  image: latest

sphinx:
  configuration: docs_old/source/conf.py

formats: all

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs_old
