language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest pytest-mock pytest-cov hypothesis
  - pip install codecov
script:
  - pytest --cov
after_success:
  - codecov
