name: publish

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Set up Python 3.x
      uses: actions/setup-python@v4.7.1
      with:
        python-version: "3.x"
    - name: Install build dependencies
      run: pip install wheel
    - name: Build packages
      run: python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
